### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by rohitdwivedula** [b-bly/simple-mern-passport#8]
Running on the command prompt produces this error: 
```> simple-mern-passport@0.1.0 dev /home/rohit/simple-mern-passport
> concurrently "react-scripts start" "nodemon server/server.js"
[1] [nodemon] 1.17.5
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: *.*
[1] [nodemon] starting `node server/server.js`
[1] App listening on PORT: 8080
[0] Starting the development server...
[0] 
[1] Connected to Mongo
[1] (node:9576) UnhandledPromiseRejectionWarning: Error: cyclic dependency detected
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:333:34)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1] (node:9576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:9576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] /home/rohit/simple-mern-passport/node_modules/mongoose/lib/utils.js:452
[1]         throw err;
[1]         ^
[1] 
[1] Error: cyclic dependency detected
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:333:34)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1]     at serializeObject (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:347:18)
[1]     at serializeInto (/home/rohit/simple-mern-passport/node_modules/bson/lib/bson/parser/serializer.js:937:17)
[1] Emitted 'error' event at:
[1]     at done (/home/rohit/simple-mern-passport/node_modules/mongoose/lib/model.js:1076:13)
[1]     at /home/rohit/simple-mern-passport/node_modules/mongoose/lib/model.js:1118:16
[1]     at /home/rohit/simple-mern-passport/node_modules/mongoose/lib/utils.js:447:16
[1]     at err (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
[1]     at session.endSession (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:399:27)
[1]     at ClientSession.endSession (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb-core/lib/sessions.js:72:41)
[1]     at executeCallback (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:397:17)
[1]     at err (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
[1]     at executeCallback (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:404:25)
[1]     at err (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:415:14)
[1]     at executeCallback (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:404:25)
[1]     at handleCallback (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)
[1]     at /home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb/lib/db.js:1068:25
[1]     at handler (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/replset.js:1211:14)
[1]     at executeWrite (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:82:5)
[1]     at WireProtocol.insert (/home/rohit/simple-mern-passport/node_modules/mongoose/node_modules/mongodb-core/lib/wireprotocol/3_2_support.js:91:3)
```

Node v11.4.0

**Comment by h4ytam** [comment]
did you bypass this error by any chance ?

**Comment by hichamfilty** [comment]
//done(err, user) instead of done(null,err)
passport.deserializeUser((id, done) => {
  console.log('deserializeUser called');
  User.findOne(
    { _id: id },
    'username',
    (err, user)=>{
      console.log('*** Deserialize user, user:')
			console.log(user)
			console.log('--------------')
			done(err, user)
    }
  )
})
